### PR TITLE
Build for 10.40 with static

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #30 

Needed for https://github.com/conda-forge/libsolv-feedstock/pull/60#issuecomment-1271414908

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
@conda-forge/pcre2 ready for review! Thanks!

**Comment by xhochy** [comment]
I'm not a big fan of explicitly listing package contents as this easily breaks. I would prefer the approach we have taken in e.g. https://github.com/conda-forge/libprotobuf-feedstock/ where we build and install everything and manually delete the static library if we build the shared version and install everything in the case of the static package. With conda-builds deduplication logic, the static version only contains the static lib. This way, we only need to list what is part of the static package and everything else is included automatically in the shared version.

**Comment by jaimergp** [comment]
Thanks!

**Pull request merged**
